project:
  type: book
  output-dir: docs 

book:
  title: "Oppimispäiväkirja: R-kielen perusteet, datankäsittely ja tilastotestit"
  author: "Aaro Pohjalainen"
  date: "08.05.2026"
  chapters:
    - index.qmd
    - part: R_kurssi/R_kurssinMT.qmd 
      chapters: 
        - R_kurssi/Osa01.qmd 
        - R_kurssi/Osa02.qmd 
        - R_kurssi/Osa03.qmd
        - R_kurssi/Osa04.qmd
        - R_kurssi/Osa05.qmd
        - R_kurssi/Osa06.qmd
    - part: Tutkimusmenetelmat_1/Tutkimusmenetelmat1.qmd
      chapters: 
        - Tutkimusmenetelmat_1/V1.qmd
        - Tutkimusmenetelmat_1/V2.qmd
        - Tutkimusmenetelmat_1/V3.qmd
    - part: R_komentoja/R_komentoja.qmd 
      chapters: 
        - R_komentoja/KuvaajienPiirto.qmd
        - R_komentoja/ggplot.qmd
        - R_komentoja/DatasetinLuominen.qmd
        - R_komentoja/Tilastotesteja.qmd
        - R_komentoja/Matemaattisia_funktioita.qmd
        - R_komentoja/Tekstikomentoja.qmd 
        - R_komentoja/Varmuuskopiointi.qmd
        - R_komentoja/Indeksointi.qmd
        - R_komentoja/FunktionLuominenJaKutsuminen.qmd
        - R_komentoja/Sekalaista.qmd
    - part: Tilastotiede/Tilastotiede.qmd
      chapters: 
        - Tilastotiede/PoikkeavatHavainnot.qmd
        - Tilastotiede/NormaalisuudenTestaaminen.qmd
        - Tilastotiede/MatematiikanLaskusääntöjä.qmd
    - references.qmd

      

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

