# Oppimispäiväkirjan esittely (LUE TÄMÄ!)  {.unnumbered}

Kirja sisältää ominaisuuksia, jotka eivät pdf versiossa toimi kunnolla, kuten lukijan ajettavissa olevia skriptejä sekä piilotettavia koodilohkoja. Siitä syystä ehdottomasti suosittelen lukemaan kirjaa verkkosivuversiona osoitteesta: <https://aaropoh.github.io/LearningDiary/>

<br>

Kirja koostuu pääasiassa muistiinpanoista liittyen Ohjelmoinnin perusteet R-ohjelmointikielellä kurssiin. Osittain kirja ei ole välttämättä erityisen kaunista luettavaa, koska asioita on kirjattu suhteellisen paljon muistiinpanotyylillä luettelemalla. Syy sille on se, että lähestyin kirjan tekemistä siitä näkökulmasta, että haluan kirjani toimivan jatkossa hakuteoksena itselleni. En niinkään siis keskittynyt tekstin viimeistelyyn tai kirjan ulkoasuun, vaan enemmänkin siihen, että olen saanut ylös mahdollisimman paljon oppimaani, jotta voin myöhemmin käyttää kirjaa apunani koodaamiseen, datan pyörittelyyn ja tilastomenetelmiin liittyvissä tehtävissä. Ajatuksenani on myös jatkaa kirjan täydentämistä seuraavillakin aiheeseen liittyvillä kursseilla.

<br>

Kirja on jaettu neljään osaan: R-kurssin tehtävät ja muistiinpanot, Tutkimusmenetelmät 1 - oppimispäiväkirja, R-komentoja sekä Tilastotiede. R-kurssin tehtävät ja muistiinpanot osio sisältää tekemäni luentomuistiinpanot, tehtävien skriptit, selitykset ja niiden lomassa opittuja asioita. Tutkimusmenetelmät 1 osio sisältää aiemman tilastokurssin muistiinpanot kokonaisuudessaan. R-komentoja ja Tilastotiede osiin olen pyrkinyt jaottelemaan kurssin mittaan opittuja R-kielen komentoja ja tilastotieteen teoriaa.
